---
- name: Install Node.js and npm
  apt:
    name:
      - nodejs
      - npm
      - git
    state: present
- name: Create application directory
  file:
    path: "{{ app_dir }}/node_app"
    state: directory
    owner: ec2-user
    group: ec2-user
    mode: '0755'
- name: Clone Node.js application repository
  git:
    repo: https://github.com/your-repo/node-app.git
    dest: "{{ app_dir }}/node_app"
    version: main
  become: yes
  become_user: ec2-user
  # Replace with your actual repository
- name: Install Node.js application dependencies
  npm:
    path: "{{ app_dir }}/node_app"
    state: present
  become: yes
  become_user: ec2-user
- name: Set database connection string in Node.js app
  lineinfile:
    path: "{{ app_dir }}/node_app/config.js"
    regexp: '^  database:'
    line: "  database: 'postgresql://{{ db_user }}:{{ db_password }}@localhost:5432/{{ db_name }}',"
  become: yes
  become_user: ec2-user
- name: Create Node.js app service
  template:
    src: node-app.service.j2
    dest: /etc/systemd/system/node-app.service
  notify: restart node app
- name: Enable and start Node.js app service
  systemd:
    name: node-app
    state: started
    enabled: yes
    daemon_reload: yes
...
